apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-test-hpa
  namespace: nginx-test
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-test-deploy
  behavior:
    scaleDown:
      policies:
        - type: Pods
          periodSeconds: 20
          value: 1
        - type: Percent
          periodSeconds: 20
          value: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10
    scaleUp:
      policies:
        - type: Pods
          periodSeconds: 20
          value: 1
        - type: Percent
          periodSeconds: 20
          value: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 10
